version: '3.3'
services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      VIRTUAL_PORT: 9000
      VIRTUAL_HOST: ${VIRTUAL_DOMAIN}
      LETSENCRYPT_HOST: ${VIRTUAL_DOMAIN}
    env_file: .env


networks:
  default:
    external:
      name: shared

volumes:
  portainer_data: